# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rpass, .registration = TRUE
NULL

#' Decrypt a binary (non-armored) OpenPGP message, as found in a `pass` `.gpg` file.
#'
#' Handles the case where the message was compressed before encryption (the
#' default when real GnuPG encrypts, even though `pass` itself disables
#' compression via `--compress-algo=none`) by calling `decompress()`, which is
#' a no-op when the message was not compressed.
decrypt_message <- function(handle, data) .Call(wrap__decrypt_message, handle, data)

#' Encrypt plaintext to one or more recipients (armored public keys), producing
#' a binary OpenPGP message compatible with the `.gpg` format used by `pass`.
encrypt_message <- function(plaintext, recipient_armors) .Call(wrap__encrypt_message, plaintext, recipient_armors)

#' Fingerprint of an armored OpenPGP public key, for matching against `.gpg-id`
#' recipient identifiers.
public_key_fingerprint <- function(armor_text) .Call(wrap__public_key_fingerprint, armor_text)

#' Generate a throwaway Ed25519/Curve25519 OpenPGP keypair for tests.
#'
#' Internal only (no `@export`): used exclusively by the testthat suite to
#' avoid ever touching a real GPG keyring or the real password store. Returns
#' an R list with `secret` and `public` armored key strings.
generate_test_keypair <- function(user_id, passphrase) .Call(wrap__generate_test_keypair, user_id, passphrase)

#' An unlocked OpenPGP secret key, held for the lifetime of an R session.
#'
#' Not exported directly to R users: `pass_key()` (R/key.R) wraps this in an
#' idiomatic S3 object. The passphrase is validated eagerly in `new()` so
#' callers get a clear error immediately instead of a confusing failure on
#' first decrypt.
#'
SecretKeyHandle <- new.env(parent = emptyenv())

SecretKeyHandle$new <- function(armor_path, passphrase) .Call(wrap__SecretKeyHandle__new, armor_path, passphrase)

SecretKeyHandle$fingerprint <- function() .Call(wrap__SecretKeyHandle__fingerprint, self)

#' @export
`$.SecretKeyHandle` <- function (self, name) { func <- SecretKeyHandle[[name]]; environment(func) <- environment(); func }

#' @export
`[[.SecretKeyHandle` <- `$.SecretKeyHandle`

# nolint end
